version: "3.8"
services:
  eureka-service:
    build: ./flight-reservation-server
    ports:
      - "8761:8761"

  gateway:
    build: ./flight-reservation-gateway
    ports:
      - "8443:8443"
    depends_on:
      - eureka-service

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - gateway
      - eureka-service

  reservation-service:
    build: ./reservation-service
    ports:
      - "8083:8083"
    depends_on:
      - gateway
      - eureka-seryavice

  flight-service:
    build: ./flight-service
    ports:
      - "8082:8082"
    depends_on:
      - gateway
      - eureka-service